### PR TITLE
Add DC Motor Code 

### PR DESCRIPTION
**Pull request by sarthakbhatkar1**

### CODE REVIEW

**Comment by aditya-c137** [comment]
Nice job sarthak... i won't accept the merge request right away let other's work first... Start with Solenoid valve next... And before starting could you tell me why use BJT and why not MOSFET in this example? Also when should one use BJT and when should one use MOSFET...

**Comment by aditya-c137** [comment]
Also go through this [link](https://chris.beams.io/posts/git-commit/) to write effective commit messages, no pressure you can take your time with this.

**Comment by sarthakbhatkar1** [comment]
> Nice job sarthak... i won't accept the merge request right away let other's work first... Start with Solenoid valve next... And before starting could you tell me why use BJT and why not MOSFET in this example? Also when should one use BJT and when should one use MOSFET..



> Nice job sarthak... i won't accept the merge request right away let other's work first... Start with Solenoid valve next... And before starting could you tell me why use BJT and why not MOSFET in this example? Also when should one use BJT and when should one use MOSFET...

**Comment by sarthakbhatkar1** [comment]
> Nice job sarthak... i won't accept the merge request right away let other's work first... Start with Solenoid valve next... And before starting could you tell me why use BJT and why not MOSFET in this example? Also when should one use BJT and when should one use MOSFET...

The used BJT is NPN transistor which acts like a switch here. So if we turn the motorPin high then the switch will be on and elsewise if it's low then switch will be off. In fewer words, we can say that BJT is current controlled-device whereas MOSFET is voltage-controlled device. However, the MOSFET's are mostly used.

**Comment by sarthakbhatkar1** [comment]
> Nice job sarthak... i won't accept the merge request right away let other's work first... Start with Solenoid valve next... And before starting could you tell me why use BJT and why not MOSFET in this example? Also when should one use BJT and when should one use MOSFET..

**Comment by aditya-c137** [comment]
> > Nice job sarthak... i won't accept the merge request right away let other's work first... Start with Solenoid valve next... And before starting could you tell me why use BJT and why not MOSFET in this example? Also when should one use BJT and when should one use MOSFET...
> 
> The used BJT is NPN transistor which acts like a switch here. So if we turn the motorPin high then the switch will be on and elsewise if it's low then switch will be off. In fewer words, we can say that BJT is current controlled-device whereas MOSFET is voltage-controlled device. However, the MOSFET's are mostly used.

cool

**Pull request merged**
